login_docker: &login_docker
  name: login docker hub
  command: |
    docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWORD}

version: 2
jobs:
  login:
    machine: true
    steps:
      - checkout
      - run: *login_docker

  deploy_sandbox:
    machine: true
    steps:
      - checkout
      - run: *login_docker
      - run: *build_docker
      - run: *sandbox_ssh

workflows:
  version: 2
  deploy:
    jobs:
      - login
      - deploy_sandbox:
          requires:
            - login
          filters:
            branches:
              only:
                - sandbox

