export const LOGIN_WITH_USERNAME_REQUEST = 'authentication/login/LOGIN_WITH_USERNAME_REQUEST'
export const LOGIN_WITH_USERNAME_SUCCESS = 'authentication/login/LOGIN_WITH_USERNAME_SUCCESS'
export const LOGIN_WITH_USERNAME_FAILURE = 'authentication/login/LOGIN_WITH_USERNAME_FAILURE'
export const LOGIN_CLOSE_MODAL = 'authentication/login/LOGIN_CLOSE_MODAL'
export const LOGOUT_USER = 'authentication/login/LOGOUT_USER'
export const CONFIRM_EMAIL_WITH_TOKEN = 'authentication/login/CONFIRM_EMAIL_WITH_TOKEN'
export const CONFIRM_EMAIL_WITH_TOKEN_SUCCESS = 'authentication/login/CONFIRM_EMAIL_WITH_TOKEN_SUCCESS'
export const CONFIRM_EMAIL_WITH_TOKEN_FAILURE = 'authentication/login/CONFIRM_EMAIL_WITH_TOKEN_FAILURE'
export const HANDLE_ALREADY_LOGIN = 'authentication/login/HANDLE_ALREADY_LOGIN'

export const REGISTER_USER_REQUEST = 'authentication/register/REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'authentication/register/REGISTER_USER_SUCCESS'
export const REGISTER_ADMIN_SUCCESS = 'authentication/register/REGISTER_ADMIN_SUCCESS'
export const REGISTER_USER_FAILURE = 'authentication/register/REGISTER_USER_FAILURE'
export const REGISTER_USER_RESET = 'authentication/register/REGISTER_USER_RESET'

export const FORGET_PASSWORD_REQUEST = 'authentication/forget-password/FORGET_PASSWORD_REQUEST'
export const FORGET_PASSWORD_SUCCESS = 'authentication/forget-password/FORGET_PASSWORD_SUCCESS'
export const CLEAR_FORGET_PASSWORD = 'authentication/forget-password/CLEAR_FORGET_PASSWORD'

export const SET_PASSWORD_REQUEST = 'authentication/set-password/SET_PASSWORD_REQUEST'
export const SET_PASSWORD_SUCCESS = 'authentication/set-password/SET_PASSWORD_SUCCESS'
export const CLEAR_SET_PASSWORD = 'authentication/set-password/CLEAR_SET_PASSWORD'
export const SET_PASSWORD_FAILURE = 'authentication/set-password/SET_PASSWORD_FAILURE'
