export const GET_USERS = 'app/admin/users/GET_USERS'
export const SET_TO_USERS = 'app/admin/users/SET_TO_USERS'
export const GET_USER = 'app/admin/users/GET_USER'
export const SET_TO_USER = 'app/admin/users/SET_TO_USER'
export const DELETE_USER = 'app/admin/users/DELETE_USER'
export const REQUEST_SUCCESS = 'app/admin/users/REQUEST_SUCCESS'

export const CREATE_YEAR = 'app/admin/year/CREATE_YEAR'
export const CREATE_YEAR_SUCCESS = 'app/admin/year/CREATE_YEAR_SUCCESS'
export const CREATE_YEAR_FAILED = 'app/admin/year/CREATE_YEAR_FAILED'
export const SET_TO_YEAR = 'app/admin/year/SET_TO_YEAR'
export const GET_YEAR_ALL = 'app/admin/year/GET_YEAR_ALL'
export const DELETE_YEAR = 'app/admin/year/DELETE_YEAR'
export const UPDATE_CURRENT_YEAR = 'app/admin/year/UPDATE_CURRENT_YEAR'
export const UPDATE_CURRENT_YEAR_SUCCESS = 'app/admin/year/UPDATE_CURRENT_YEAR_SUCCESS'