export const GET_USERS = 'app/admin/users/GET_USERS'
export const SET_TO_USERS = 'app/admin/users/SET_TO_USERS'
export const GET_USER = 'app/admin/users/GET_USER'
export const SET_TO_USER = 'app/admin/users/SET_TO_USER'
export const DELETE_USER = 'app/admin/users/DELETE_USER'
export const DELETE_USER_SUCCESS = 'app/admin/users/DELETE_USER_SUCCESS'
export const REQUEST_SUCCESS = 'app/admin/users/REQUEST_SUCCESS'

export const CREATE_YEAR = 'app/admin/year/CREATE_YEAR'
export const CREATE_YEAR_SUCCESS = 'app/admin/year/CREATE_YEAR_SUCCESS'
export const CREATE_YEAR_FAILED = 'app/admin/year/CREATE_YEAR_FAILED'
export const SET_TO_YEAR = 'app/admin/year/SET_TO_YEAR'
export const GET_YEAR_ALL = 'app/admin/year/GET_YEAR_ALL'
export const DELETE_YEAR = 'app/admin/year/DELETE_YEAR'
export const DELETE_YEAR_SUCCESS = 'app/admin/year/DELETE_YEAR_SUCCESS'
export const UPDATE_CURRENT_YEAR = 'app/admin/year/UPDATE_CURRENT_YEAR'
export const UPDATE_CURRENT_YEAR_SUCCESS = 'app/admin/year/UPDATE_CURRENT_YEAR_SUCCESS'
export const GET_CURRENT_YEAR = 'app/admin/year/GET_CURRENT_YEAR'
export const SET_CURRENT_YEAR = 'app/admin/year/SET_CURRENT_YEAR'

export const GET_BEACON_ALL = 'app/admin/beacon/GET_BEACON_ALL'
export const SET_TO_BEACON = 'app/admin/beacon/SET_TO_BEACON'
export const DELETE_BEACON = 'app/admin/beacon/DELETE_BEACON'
export const DELETE_TO_BEACON = 'app/admin/beacon/DELETE_TO_BEACON'

export const CLEAR_HISTORY = 'app/admin/datateachingHistory/CLEAR_HISTORY'
export const CLEAR_HISTORY_SUCCESS = 'app/admin/datateachingHistory/CLEAR_HISTORY_SUCCESS'

